<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net6.0-windows</TargetFramework><UseWPF>true</UseWPF><EnableDefaultCompileItems>false</EnableDefaultCompileItems><Nullable>enable</Nullable><RollForward>Major</RollForward></PropertyGroup>
  <ItemGroup><Compile Include="AtomicUploadChecks.cs.txt"/><ProjectReference Include="..\..\FileToGitHub.csproj"/></ItemGroup>
</Project>
